package com.ehuizhen.weixin.model;
// Generated 2016-2-1 16:25:37 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;


/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog="wxdb")
public class UserModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8151130661206418277L;
	private int id;
	private String wxid;
	private String name;
	private String mobile;
	private Character sex;
	private String companyName;
	private String position;
	private String business;
	private String hobby;
	private String email;
	private String address;
	private String signs;
	private String signature;
	private char level;
	private char status = '1';
	private Date inDate;
	private Date vIPExpireTime;
	
	public UserModel() {
	}

	public UserModel(String wxid, String name, String mobile, char level, Date inDate, Date vIPExpireTime) {
		this.wxid = wxid;
		this.name = name;
		this.mobile = mobile;
		this.level = level;
		this.inDate = inDate;
		this.vIPExpireTime = vIPExpireTime;
	}

	public UserModel(String wxid, String name, String mobile, Character sex, String companyName, String position,
			String business, String hobby, String email, String address, String signs, String signature, char level,
			Date inDate, Date vIPExpireTime) {
		this.wxid = wxid;
		this.name = name;
		this.mobile = mobile;
		this.sex = sex;
		this.companyName = companyName;
		this.position = position;
		this.business = business;
		this.hobby = hobby;
		this.email = email;
		this.address = address;
		this.signs = signs;
		this.signature = signature;
		this.level = level;
		this.inDate = inDate;
		this.vIPExpireTime = vIPExpireTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "WXID")
	public String getWxid() {
		return this.wxid;
	}

	public void setWxid(String wxid) {
		this.wxid = wxid;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Mobile", nullable = false, length = 11)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "Sex", length = 1)
	public Character getSex() {
		return this.sex;
	}

	public void setSex(Character sex) {
		this.sex = sex;
	}

	@Column(name = "CompanyName")
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "Position")
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "Business")
	public String getBusiness() {
		return this.business;
	}

	public void setBusiness(String business) {
		this.business = business;
	}

	@Column(name = "Hobby")
	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "Signs")
	public String getSigns() {
		return this.signs;
	}

	public void setSigns(String signs) {
		this.signs = signs;
	}

	@Column(name = "Signature")
	public String getSignature() {
		return this.signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	@Column(name = "Level", nullable = false, length = 1)
	public char getLevel() {
		return this.level;
	}

	public void setLevel(char level) {
		this.level = level;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InDate", nullable = false, length = 19)
	public Date getInDate() {
		return this.inDate;
	}

	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VIPExpireTime", nullable = false, length = 19)
	public Date getvIPExpireTime() {
		return vIPExpireTime;
	}

	public void setvIPExpireTime(Date vIPExpireTime) {
		this.vIPExpireTime = vIPExpireTime;
	}
	
	@Column(name = "Status", nullable = false, length = 1)
	public char getStatus() {
		return status;
	}

	public void setStatus(char status) {
		this.status = status;
	}
	
	private List<BrowseHistoryModel> historyInfo = new ArrayList<BrowseHistoryModel>();
	
	@OneToMany(targetEntity = BrowseHistoryModel.class, cascade = CascadeType.REFRESH, fetch = FetchType.EAGER)
	@JoinColumn(name = "userId", updatable = false, insertable = false, referencedColumnName = "id")
	public List<BrowseHistoryModel> getHistoryInfo() {
		return this.historyInfo;
	}

	public void setHistoryInfo(List<BrowseHistoryModel> historyInfo) {
		this.historyInfo = historyInfo;
	}
	
	private String wxurl;
	private String nickName;
	private String verifyCode;
	
	@Transient
	public String getWxurl() {
		return this.wxurl;
	}
	
	public void setWxurl(String wxurl) {
		this.wxurl = wxurl;
	}
	
	@Transient
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}
	
	@Transient
	public String getVerifyCode() {
		return this.verifyCode;
	}

	public void setVerifyCode(String verifyCode) {
		this.verifyCode = verifyCode;
	}
}
