package com.ehuizhen.weixin.model;
// Generated 2015-11-16 12:19:10 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sms generated by hbm2java
 */
@Entity
@Table(name = "SMS")//catalog="ehuizhen_test" , catalog="ehuizhen"
public class SmsModel implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 6605296400541722909L;
	private int id;
	//@ApiParam(name="短信类型")
	private int type;
	//@ApiParam(name="手机号码")
	private String mobile;
	//@ApiParam(name="短信内容")
	private String noteContent;
	//@ApiParam(name="验证码")
	private String verifyCode;
	//@ApiParam(name="过期时间")
	private Date expTime;
	//@ApiParam(name="状态")
	private Integer status;
	//@ApiParam(name="发送时间")
	private Date sendTime;
	//@ApiParam(name="重试次数")
	private Integer retryCount;
	private int inUser;
	private Date inDate;
	private int editUser;
	private Date editDate;

	public SmsModel() {
	}

	public SmsModel(int id, Date inDate, Date editDate) {
		this.id = id;
		this.inDate = inDate;
		this.editDate = editDate;
	}

	public SmsModel(int id,int type, String mobile, String noteContent, String verifyCode, Date expTime, Integer status,
			Integer retryCount, int inUser, Date inDate, int editUser, Date editDate, Date sendTime) {
		this.id = id;
		this.type = type;
		this.mobile = mobile;
		this.noteContent = noteContent;
		this.verifyCode = verifyCode;
		this.expTime = expTime;
		this.status = status;
		this.retryCount = retryCount;
		this.inUser = inUser;
		this.inDate = inDate;
		this.editUser = editUser;
		this.editDate = editDate;
		this.sendTime = sendTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "Type", nullable = false)
	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "Mobile", length = 11)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "NoteContent", length = 200)
	public String getNoteContent() {
		return this.noteContent;
	}

	public void setNoteContent(String noteContent) {
		this.noteContent = noteContent;
	}

	@Column(name = "VerifyCode", length = 10)
	public String getVerifyCode() {
		return this.verifyCode;
	}

	public void setVerifyCode(String verifyCode) {
		this.verifyCode = verifyCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ExpTime", length = 19)
	public Date getExpTime() {
		return this.expTime;
	}

	public void setExpTime(Date expTime) {
		this.expTime = expTime;
	}

	@Column(name = "Status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "RetryCount")
	public Integer getRetryCount() {
		return this.retryCount;
	}

	public void setRetryCount(Integer retryCount) {
		this.retryCount = retryCount;
	}

	@Column(name = "InUser", nullable = false)
	public int getInUser() {
		return this.inUser;
	}

	public void setInUser(int inUser) {
		this.inUser = inUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InDate", nullable = false, length = 19)
	public Date getInDate() {
		return this.inDate;
	}

	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

	@Column(name = "EditUser", nullable = false)
	public int getEditUser() {
		return this.editUser;
	}

	public void setEditUser(int editUser) {
		this.editUser = editUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EditDate", nullable = false, length = 19)
	public Date getEditDate() {
		return this.editDate;
	}

	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SendTime", length = 19)
	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}
}
