package com.ehuizhen.weixin.model;
// Generated 2016-3-3 16:48:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * CourseAssist generated by hbm2java
 */
@Entity
@Table(name = "CourseAssist")
public class CourseAssistModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4171668341206866810L;
	private int id;
	private int courseId;
	private String descript;
	private String url;
	private int type;
	private String status;
	private Date inDate;
	private int inUser;

//	private CourseModel courseInfo;
//
//	@OneToOne(cascade = CascadeType.REFRESH, fetch = FetchType.EAGER, targetEntity = CourseModel.class)
//	@NotFound(action = NotFoundAction.IGNORE)
//	@JoinColumn(name = "courseId", updatable = false, insertable = false)
//	public CourseModel getCourseInfo() {
//		return courseInfo;
//	}
//	public void setCourseInfo(CourseModel courseInfo) {
//		this.courseInfo = courseInfo;
//	}

	public CourseAssistModel() {
	}

	public CourseAssistModel(int id, int courseId, int type, String status, Date inDate, int inUser) {
		this.id = id;
		this.courseId = courseId;
		this.type = type;
		this.status = status;
		this.inDate = inDate;
		this.inUser = inUser;
	}

	public CourseAssistModel(int id, int courseId, String descript, String url, int type, String status, Date inDate,
			int inUser) {
		this.id = id;
		this.courseId = courseId;
		this.descript = descript;
		this.url = url;
		this.type = type;
		this.status = status;
		this.inDate = inDate;
		this.inUser = inUser;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "CourseId", nullable = false)
	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	@Column(name = "Descript", length = 500)
	public String getDescript() {
		return this.descript;
	}

	public void setDescript(String descript) {
		this.descript = descript;
	}

	@Column(name = "Url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "Type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "Status", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InDate", nullable = false, length = 19)
	public Date getInDate() {
		return this.inDate;
	}

	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

	@Column(name = "InUser", nullable = false)
	public int getInUser() {
		return this.inUser;
	}

	public void setInUser(int inUser) {
		this.inUser = inUser;
	}

}
