package com.ehuizhen.weixin.model;
// Generated 2016-2-1 16:25:37 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "DoctorAudit")//catalog="ehuizhen_test" , catalog="ehuizhen"
public class DoctorAuditModel implements java.io.Serializable {

	private static final long serialVersionUID = 8151130661206418277L;
	private int id;
	private String doctorName;
	private String phoneNum;
	private int sex;//性别1:女 2:男
	private String email;
	private String idCard;//身份证号
	private String doctorCertNo;//医生职业证书编号
	private String hospital;//所在医院
	private String department;//所在科室
	private String position;//职称
	private String skilledField;//擅长领域
	private String selfIntro;//个人介绍
	private String selfPhotoUrl;//个人照片
	private String chargingStandard;//收费标准
	private int status;//0:未审核；1:审核通过 2:审核未通过
	private int oversea;//0:国内 1:在海外
	private String wxOpenId;//此用户微信 openId
	private Date inDate;//录入时间
	private Date auditDate;//审核日期
	private int auditUserId;//审核人
	
	public DoctorAuditModel() {
	}
	

	public DoctorAuditModel(String doctorName, String phoneNum, int sex, String idCard, int oversea, Date inDate,int status) {
		super();
		this.doctorName = doctorName;
		this.phoneNum = phoneNum;
		this.sex = sex;
		this.idCard = idCard;
		this.oversea = oversea;
		this.inDate = inDate;
		this.status = status;
	}


	public DoctorAuditModel(String doctorName, String phoneNum, int sex, String idCard, String hospital,
			String department, String position, String skilledField, String selfIntro, String selfPhotoUrl, int status,
			int oversea, String wxOpenId, Date inDate) {
		super();
		this.doctorName = doctorName;
		this.phoneNum = phoneNum;
		this.sex = sex;
		this.idCard = idCard;
		this.hospital = hospital;
		this.department = department;
		this.position = position;
		this.skilledField = skilledField;
		this.selfIntro = selfIntro;
		this.selfPhotoUrl = selfPhotoUrl;
		this.status = status;
		this.oversea = oversea;
		this.wxOpenId = wxOpenId;
		this.inDate = inDate;
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "DoctorName", nullable = false)
	public String getDoctorName() {
		return this.doctorName;
	}
	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}
	
	@Column(name = "PhoneNum", nullable = false)
	public String getPhoneNum() {
		return this.phoneNum;
	}
	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}
	
	@Column(name = "Sex", nullable = false)
	public int getSex() {
		return this.sex;
	}
	public void setSex(int sex) {
		this.sex = sex;
	}
	@Column(name = "Email", nullable = true)//可为空
	public String getEmail() {
		return this.email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	
	@Column(name = "IdCard", nullable = false)
	public String getIdCard() {
		return this.idCard;
	}
	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}
	
	@Column(name = "DoctorCertNo", nullable = true)//可为空
	public String getDoctorCertNo() {
		return this.doctorCertNo;
	}
	public void setDoctorCertNo(String doctorCertNo) {
		this.doctorCertNo = doctorCertNo;
	}
	
	@Column(name = "Hospital", nullable = false)
	public String getHospital() {
		return this.hospital;
	}
	public void setHospital(String hospital) {
		this.hospital = hospital;
	}
	
	@Column(name = "Department", nullable = false)
	public String getDepartment() {
		return this.department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	
	@Column(name = "Position", nullable = false)
	public String getPosition() {
		return this.position;
	}
	public void setPosition(String position) {
		this.position = position;
	}
	
	@Column(name = "SkilledField", nullable = false)
	public String getSkilledField() {
		return this.skilledField;
	}
	public void setSkilledField(String skilledField) {
		this.skilledField = skilledField;
	}
	
	@Column(name = "SelfIntro", nullable = false)
	public String getSelfIntro() {
		return this.selfIntro;
	}
	public void setSelfIntro(String selfIntro) {
		this.selfIntro = selfIntro;
	}
	
	@Column(name = "SelfPhotoUrl", nullable = false)
	public String getSelfPhotoUrl() {
		return this.selfPhotoUrl;
	}
	public void setSelfPhotoUrl(String selfPhotoUrl) {
		this.selfPhotoUrl = selfPhotoUrl;
	}
	
	@Column(name = "ChargingStandard", nullable = true)//可为空
	public String getChargingStandard() {
		return this.chargingStandard;
	}
	public void setChargingStandard(String chargingStandard) {
		this.chargingStandard = chargingStandard;
	}
	
	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}
	public void setStatus(int status) {
		this.status = status;
	}
	
	@Column(name = "Oversea", nullable = false)
	public int getOversea() {
		return this.oversea;
	}
	public void setOversea(int oversea) {
		this.oversea = oversea;
	}
	
	@Column(name = "WxOpenId", nullable = true)//可为空
	public String getWxOpenId() {
		return this.wxOpenId;
	}
	public void setWxOpenId(String wxOpenId) {
		this.wxOpenId = wxOpenId;
	}
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InDate", nullable = true)
	public Date getInDate() {
		return this.inDate;
	}
	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AuditDate", nullable = false)//可为null
	public Date getAuditDate() {
		return this.auditDate;
	}
	public void setAuditDate(Date auditDate) {
		this.auditDate = auditDate;
	}
	
	
	@Column(name = "AuditUserId", nullable = true)//可为空
	public int getAuditUserId() {
		return this.auditUserId;
	}
	public void setAuditUserId(int auditUserId) {
		this.auditUserId = auditUserId;
	}


	@Override
	public String toString() {
		return "DoctorAuditModel [id=" + id + ", doctorName=" + doctorName + ", phoneNum=" + phoneNum + ", sex=" + sex
				+ ", email=" + email + ", idCard=" + idCard + ", doctorCertNo=" + doctorCertNo + ", hospital="
				+ hospital + ", department=" + department + ", position=" + position + ", skilledField=" + skilledField
				+ ", selfIntro=" + selfIntro + ", selfPhotoUrl=" + selfPhotoUrl + ", chargingStandard="
				+ chargingStandard + ", status=" + status + ", oversea=" + oversea + ", wxOpenId=" + wxOpenId
				+ ", inDate=" + inDate + ", auditDate=" + auditDate + ", auditUserId=" + auditUserId + "]";
	}

	

/**
 
 	CREATE TABLE IF NOT EXISTS `DoctorAudit` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DoctorName` varchar(50) NOT NULL COMMENT '医生姓名',
  `PhoneNum` varchar(30) NOT NULL COMMENT '手机号',
  `Sex` int(11) NOT NULL DEFAULT '0' COMMENT '性别1:女 2:男',
  `Email` varchar(50) DEFAULT NULL COMMENT '邮箱，海外用户校验，国内用户可选',
  `IdCard` varchar(50) NOT NULL COMMENT '身份证',
  `DoctorCertNo` varchar(100) NOT NULL COMMENT '医生职业证书编号',
  `Hospital` varchar(100) NOT NULL COMMENT '所在医院',
  `Department` varchar(50) NOT NULL COMMENT '所在科室',
  `Position` varchar(50) NOT NULL COMMENT '职称',
  `SkilledField` varchar(200) NOT NULL COMMENT '擅长领域',
  `SelfIntro` varchar(200) NOT NULL COMMENT '个人介绍',
  `SelfPhotoUrl` varchar(200) NOT NULL COMMENT '个人照片',
  `ChargingStandard` varchar(50) DEFAULT NULL COMMENT '收费标准，海外用户有自己的收费标准，国内用户按统一标准',
  `Status` int(11) NOT NULL DEFAULT '0' COMMENT '0:未审核；1:审核通过 2:审核未通过',
  `Oversea` int(11) NOT NULL DEFAULT '0' COMMENT '0:国内 1:在海外 ',
  `WxOpenId` varchar(30) DEFAULT NULL COMMENT '微信OpenId',
  `InDate` timestamp NULL DEFAULT '0000-00-00 00:00:00' COMMENT '录入时间',
  `AuditDate` timestamp NULL DEFAULT '0000-00-00 00:00:00' COMMENT '审核时间',
  `AuditUserId` int(11) DEFAULT '0' COMMENT '审核人Id',
 */
	
}
