package com.ehuizhen.weixin.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* User generated by hbm2java
*/
@Entity        
@Table(name = "DoctorPasswdModifyLinkToken")
public class DoctorPasswdModifyLinkToken implements java.io.Serializable {


	private Integer id;
	
	private String linkTokenkey;//分+randomNum
	
	private int status;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	
	
	@Column(name = "Status")
	public int getStatus() {
		return this.status;
	}

	@Column(name = "LinkTokenkey", nullable = false)
	public String getLinkTokenkey() {
		return linkTokenkey;
	}
	public void setLinkTokenkey(String linkTokenkey) {
		this.linkTokenkey = linkTokenkey;
	}
	public void setStatus(int status) {
		this.status = status;
	}

	public DoctorPasswdModifyLinkToken() {
	}
	public DoctorPasswdModifyLinkToken(String key, int status) {
		this.linkTokenkey = key;
		this.status = status;
	}
	
	
}
