package com.ehuizhen.weixin.model;
// Generated 2016-2-1 16:25:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "Feedback", catalog="wxdb")
public class FeedbackModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5370806734436916172L;
	private Integer id;
	private String userName;
	private String userMobile;
	private String description;
	private String advice;
	private Date inDate;

	public FeedbackModel() {
	}

	public FeedbackModel(String description, String advice, Date inDate) {
		this.description = description;
		this.advice = advice;
		this.inDate = inDate;
	}

	public FeedbackModel(String userName, String userMobile, String description, String advice, Date inDate) {
		this.userName = userName;
		this.userMobile = userMobile;
		this.description = description;
		this.advice = advice;
		this.inDate = inDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "UserName")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "UserMobile")
	public String getUserMobile() {
		return this.userMobile;
	}

	public void setUserMobile(String userMobile) {
		this.userMobile = userMobile;
	}

	@Column(name = "Description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Advice", nullable = false)
	public String getAdvice() {
		return this.advice;
	}

	public void setAdvice(String advice) {
		this.advice = advice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InDate", nullable = false, length = 19)
	public Date getInDate() {
		return this.inDate;
	}

	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

}
