package com.ehuizhen.weixin.model;
// Generated 2016-2-4 9:54:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Config generated by hbm2java
 */
@Entity
@Table(name = "SysConfig", catalog="wxdb")
public class ConfigModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6641349557241289869L;
	private Integer id;
	private String name;
	private String content;
	private String note;
	private int inUser;
	private Date inDate;
	private int editUser;
	private Date editDate;

	public ConfigModel() {
	}

	public ConfigModel(String name, String content, int inUser, Date inDate, int editUser, Date editDate) {
		this.name = name;
		this.content = content;
		this.inUser = inUser;
		this.inDate = inDate;
		this.editUser = editUser;
		this.editDate = editDate;
	}

	public ConfigModel(String name, String content, String note, int inUser, Date inDate, int editUser, Date editDate) {
		this.name = name;
		this.content = content;
		this.note = note;
		this.inUser = inUser;
		this.inDate = inDate;
		this.editUser = editUser;
		this.editDate = editDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Lob
	@Column(name = "Content", nullable = false)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "Note", length = 100)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "InUser", nullable = false)
	public int getInUser() {
		return this.inUser;
	}

	public void setInUser(int inUser) {
		this.inUser = inUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InDate", nullable = false, length = 19)
	public Date getInDate() {
		return this.inDate;
	}

	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

	@Column(name = "EditUser", nullable = false)
	public int getEditUser() {
		return this.editUser;
	}

	public void setEditUser(int editUser) {
		this.editUser = editUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EditDate", nullable = false, length = 19)
	public Date getEditDate() {
		return this.editDate;
	}

	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

}
